# Capstone Report: Analyzing World Data to Determine Problem Areas for Effective Altruism Initiatives and See Which Cities Offer High Impact Jobs

<h3>Problem description</h3>
I have decided to use this capstone project to address a dilemma an altruistic young human being (say, a senior year student or a recent graduate) can have: how to choose a career which would allow her or him to contribute to solving some of the world's biggest challenges? At least, some questions should come to mind:
<ul>
 	<li>What are the world’s biggest challenges?</li>
 	<li>How can I contribute to solve at least one of them?</li>
 	<li>What career path should I choose to be able to contribute either financially or through research and impactful work?</li>
</ul>
People spend more time on their jobs than on any other activity besides sleeping—roughly 80,000 hours over the course of their lives. Choosing the right career, therefore, may be one of the most impactful things an altruistically-motivated person can do.
In my capstone project, I have chosen to, at least, partially, address these questions.
<h3>Data and Methodology</h3>

In this project, I have chosen to:

1) look at<a href="https://www.kaggle.com/worldbank/world-development-indicators"> the World Development Indicators Database</a> to see which areas need more attention of the EA community, not just organizations but individuals willing to contribute to solving some of these challenges either through donations or working in NGOs in those areas.

I'll use Python to study the data and single out 20 poorest countries. I'll also look at immunization data, death rates and health expenditures. I'll use Matplotlib and Folium maps to visualize the data.

2) scrape <a href="https://80000hours.org/job-board/">the High impact job board</a> created by 80,000 Hours Initiative, geocode the data and visualize it to see where high impact jobs are available. For this I use Selenium and webdriver.

Then I will use Folium map not just to visualize but also to cluster job offers and see which city has more to offer for effective altuist job seeker.

Having selected the city with the biggest number of offers, I will use Foursquare API to return the list of venues in the city center. I will also use Foursquare API to see which venues are trending at the moment.

Additionally, I will use a json of countries' coordinates and will scrape <a href="https://en.wikipedia.org/wiki/List_of_African_countries_by_population">a list of African countries from Wikipedia</a> and merge it with our dataset.

<strong>Methodology explained</strong>

Effective Altruism community extensively uses statistical data to determine the most effective ways to address the biggest challenges the world currently faces. Hence, I have chosen to use the primary World Bank collection of development indicators, compiled from officially-recognized international sources. It presents the most current and accurate global development data available, and includes national, regional and global estimates.

We will use Python and Pandas extensively throughout our analysis. Matplotlib and Folium maps will be used for visualization.

First we will use Pandas to retrieve and structure our data. We will return a list of indicators. The list is huge and we will manually study what is available and choose the areas we will concentrate on.

&nbsp;

<h3>Results</h3>

The analysis has shown that following countries had the lowest GNI per capita in 2014:

In [2]:
import folium
import pandas as pd
from IPython.display import HTML
import requests
from pandas.io.json import json_normalize
import numpy as np
%matplotlib inline 

import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
# Read in the World Development Indicators Database
data = pd.read_csv('Indicators.csv')
data.shape

(5656458, 6)

In [4]:
lowestGNIin2014 = data.query("IndicatorCode == 'NY.GNP.PCAP.CD' & CountryName != list & Year == 2014").sort_values(by = 'Value', ascending = True)[:20]
lowestGNIin2014

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
5599036,Malawi,MWI,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,250.000000
5560090,Burundi,BDI,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,270.000000
5562875,Central African Republic,CAF,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,320.000000
5595779,Liberia,LBR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,370.000000
5566237,"Congo, Dem. Rep.",ZAR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,380.000000
5609975,Niger,NER,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,410.000000
5598471,Madagascar,MDG,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,440.000000
5581393,Guinea,GIN,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,470.000000
5574999,Ethiopia,ETH,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,550.000000
5581914,Guinea-Bissau,GNB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,550.000000
5632291,Togo,TGO,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,570.000000
5606487,Mozambique,MOZ,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,600.000000
5540744,Low income,LIC,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,628.609002
5600792,Mali,MLI,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,650.000000
5635390,Uganda,UGA,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,670.000000
5546512,Afghanistan,AFG,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,680.000000
5618233,Rwanda,RWA,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,700.000000
5621783,Sierra Leone,SLE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,700.000000
5559513,Burkina Faso,BFA,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,700.000000
5607879,Nepal,NPL,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2014,730.000000

Unlike GDP, GNI measures all income of a country's residents and businesses, regardless of where it's produced. Including income from investments, GNI measures income earned that flows back into the country. 

GNI per capita is a measurement of income divided by the number of people in the country. It compares the GNI of countries with different population sizes and standards of living. 

The World Bank provides this data converting income to U.S. dollars using the official exchange rate.  That is why this particular indicator was chosen for analysis.

<b>Some of the biggest problems to address</b>

As seen on Folium maps in the capstone project notebook, countries with low GNI per capita tend to have a range of problems which need to be addressed. 

We used Folium maps to demonstrate some of these challenges: high mortality rates, low health expenditure and poor immunization numbers. Vaccination data were especially troubling in South Sudan, Equatorial Guinea and Somalia.

EA movement has a lot of affinity to the philosophy of utilitarianism. It is generally held to be the view that the morally right action is the action that produces the most good. On the utilitarian view one ought to maximize the overall good — that is, consider the good of others as well as one's own good. Utilitarian philosophers often talk about happiness as something we ought to maximize. 

But what is happiness? How can it be measured? There is significant evidence that happier people are healthier, more productive and more resilient to external shocks (for example, unemployment). There have been enormous advances in the measurement of human well-being over the last couple of decades. 

Access to healthcare is an important factor. Let's see which countries perform the worst.

In [13]:
HospitalBedsin2012 = data.query("IndicatorName == 'Hospital beds (per 1,000 people)' & CountryName != list & Year == 2012").sort_values(by = 'Value', ascending = True)[:20]
HospitalBedsin2012

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
5288805,"Iran, Islamic Rep.",IRN,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.100000
5224016,Afghanistan,AFG,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.500000
5266366,"Egypt, Arab Rep.",EGY,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.500000
5329598,Pakistan,PAK,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.600000
5375269,"Yemen, Rep.",YEM,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.700000
5283851,Honduras,HND,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.700000
5354487,Sudan,SDN,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.800000
5216099,Middle East & North Africa (developing only),MNA,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.814026
5325481,Nicaragua,NIC,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.900000
5319728,Morocco,MAR,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.900000
5287933,Indonesia,IDN,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,0.900000
5215498,Middle East & North Africa (all income levels),MEA,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.014778
5368776,United Arab Emirates,ARE,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.100000
5236741,Belize,BLZ,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.100000
5267390,El Salvador,SLV,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.100000
5240003,Bolivia,BOL,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.100000
5202488,Arab World,ARB,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.148700
5257454,Costa Rica,CRI,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.200000
5337316,Qatar,QAT,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.200000
5348220,Solomon Islands,SLB,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,2012,1.300000

As we can see, some of the worst performing countries are also among the poorest. 

As it comes to unemployment statistics, we see a different set of countries, but the also rank low on the happiness index: https://en.wikipedia.org/wiki/World_Happiness_Report

In [15]:
Unemployment = data.query("IndicatorName == 'Unemployment, total (% of total labor force)' & CountryName != list & Year == 2014").sort_values(by = 'Value', ascending = False)[:20]
Unemployment

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
5602193,Mauritania,MRT,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,31.000000
5557163,Bosnia and Herzegovina,BIH,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,27.900000
5598281,"Macedonia, FYR",MKD,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,27.900000
5579984,Greece,GRC,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,26.299999
5595599,Lesotho,LSO,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,26.200001
5640148,West Bank and Gaza,WBG,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,26.200001
5624949,South Africa,ZAF,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,25.100000
5625639,Spain,ESP,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,24.700001
5606876,Mozambique,MOZ,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,22.600000
5628768,Swaziland,SWZ,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,22.299999
5621333,Serbia,SRB,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,22.200001
5577393,Gabon,GAB,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,19.700001
5596411,Libya,LBY,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,19.200001
5605657,Montenegro,MNE,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,19.100000
5607680,Namibia,NAM,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,18.600000
5557708,Botswana,BWA,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,18.200001
5640543,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,17.400000
5549922,Armenia,ARM,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,17.100000
5568819,Croatia,HRV,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,16.700001
5587273,Iraq,IRQ,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2014,16.400000

<h3>Discussion</h3>

You can see a much more detailed analysis in the Capstone project notebook. In that notebook, we have extracted a number of areas to address for effective altruists,  scraped all the job locations from 80,000 Hours job board, geocoded them and clustered on a map. 

San Francisco came as a winner. Hence we used Foursquare API to see which venues are available in the city center and which are trending.

<h3>Conclusion</h3>

Effective altruism helps the world by causing individuals to do more good in their lives. Data science is an indispensable set of skills which can help an effective altruism to succeed in her or his mission. This capstone project is just the beginning of this analysis. I hope it helps and motivates someone to explore further.